don't use libshell

diff --git a/slazav-ph-scripts/pd/pd_init b/slazav-ph-scripts/pd/pd_init
--- a/slazav-ph-scripts/pd/pd_init
+++ b/slazav-ph-scripts/pd/pd_init
@@ -1,7 +1,5 @@
 #!/bin/sh -eu
 
-. shell-error
-
 # normalize photo names, autorotate, create archive copy in .src directory
 
 count=0
@@ -28,13 +26,13 @@ for i in $(find . -maxdepth 1 -name '*.JPG' -or -name '*.jpg'); do
       fi
     done
   fi
-  [ ! -f "$n" ] || fatal "Can't find uniq name for $i!"
+  [ ! -f "$n" ] || { printf "Can't find uniq name for $i!\n"; exit 1; }
 
   mv "$i" "$n"
   echo "Renaming $i to $n..."
 done
 
-[ "$count" != 0 ] || fatal "No jpeg files found!"
+[ "$count" != 0 ] || { printf "No jpeg files found!\n"; exit 1; }
 
 echo "$count jpeg files found"
 
